apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-5
  labels:
    app: nginx-app-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-5
  template:
    metadata:
      labels:
        app: nginx-app-5
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
